[project]
name = "wikitermbase"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "arabterm @ git+https://github.com/forzagreen/arabterm.git",
    "fastapi",
    "gunicorn",
    "pandas",
    "pymysql",
    "sentry-sdk[fastapi]",
    "sqlalchemy",
    "uvicorn[standard]",
]

[dependency-groups]
dev = [
    "ipykernel",
    "pytest",
    "ruff",
]
